export enum SortTypeNames {
	titleAsc = 'Название',
	titleDesc = 'Название',
	// userAsc = 'Автор',
	// userDesc = 'Автор',
	repeatableAsc = 'Многократное',
	repeatableDesc = 'Многократное',
	greenwichAsc = 'Глобальное',
	greenwichDesc = 'Глобальное',
	publicAsc = 'Публичное',
	publicDesc = 'Публичное',
	closestAsc = 'Ближайшее',
	closestDesc = 'Ближайшее',
	directionAsc = 'Прошлое',
	directionDesc = 'Будущее',
}
