export enum SortTypeNames {
	titleAsc = 'Название',
	titleDesc = 'Название',
	// userAsc = 'Автор',
	// userDesc = 'Автор',
	repeatableAsc = 'Повторяемое',
	repeatableDesc = 'Повторяемое',
	greenwichAsc = 'Гринвич',
	greenwichDesc = 'Гринвич',
	publicAsc = 'Публичное',
	publicDesc = 'Публичное',
	closestAsc = 'Ближайшее',
	closestDesc = 'Ближайшее',
	directionAsc = 'Направление',
	directionDesc = 'Направление',
}
