name: DEPLOY CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: npm cache clean --force
    - run: rm -rf node_modules package-lock.json
    #- run: npm test

    - name: Deploy to external server via SFTP
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
        DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}

      run: |
        sshpass -p "$SSH_PASS" rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dist/cd/ $SSH_USER@$SSH_HOST:$DEPLOY_PATH
